name: Test Docusaurus Build

on:
  pull_request:
    branches:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install
      - name: Build API docs
        run: npm run docusaurus gen-api-docs all
      - name: Build
        run: npm run build


    
      - name: Get list of changed files
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff --name-only origin/${{ github.event.pull_request.base.ref }}...${{ github.sha }} > changed_files.txt
          

      - name: Check filenames
        run: |
          invalid_files=()
          while IFS= read -r file; do
            filename=$(basename "$file")
            if ! [[ "$filename" =~ ^[a-zA-Z0-9._-]+$ ]]; then
              invalid_files+=("$file")
            fi
          done < changed_files.txt

          if [ ${#invalid_files[@]} -ne 0 ]; then
            echo "The following file names contain invalid characters:"
            for f in "${invalid_files[@]}"; do
              echo "  - $f"
            done
            exit 1
          fi
